### ISSUE TITLE
Robust PCA demo on cvxr website with increasing objective value

### ISSUE THREAD

**Issue by iverson333** [cvxr/TFOCS#15]
Hi there, I'm interested in applying RPCA method implemented in TFOCS to my research project. However when I checked the  [demo on cvx's website](http://cvxr.com/tfocs/demos/rpca/), it shows that the objective function is actually increasing as it iterates. I wonder why is this the case. More specifically, we are minimizing the objective function, why it is increasing?

**Comment by stephenbeckr** [comment]
If that happens all the time, it's probably an issue, but if it only happens sometimes, it's probably just because Nesterov accelerated methods are not monotonic. Basically, in exchange for faster overall convergence, sometimes they take steps that appear to be worse.

**Comment by iverson333** [comment]
From the snapshot of the printout info of RPCA on the [demo website](http://cvxr.com/tfocs/demos/rpca/) as below (and similarly on my computer every time I try it) it looks like the objective is monotonically increasing....

<img width="432" alt="rpca_printout" src="https://user-images.githubusercontent.com/34754010/88467812-f5efcc80-ce8f-11ea-99e6-f88178878efe.png">

**Comment by stephenbeckr** [comment]
Ok, then I think the issue is just that the demo calls the `tfocs_SCD` version, which solves the dual problem, and the way we write the dual (Lagrangian duality), we want to maximize the dual function (which is concave, hence equivalent to minimizing a convex function).  Hence we are doing gradient **ascent** here, and that's why the objective is increasing.  You can see that the errors are decaying, so that's a sign that everything is working properly.
