### ISSUE TITLE
Enable matrix input to prox_l1

### ISSUE THREAD

**Issue by Nick3151** [cvxr/TFOCS#16]
Hi, I am using matrix X as input, and my non-smooth function is the sum of the absolute value of all the non-diagonal indices of X. This should be done with function prox_l1(q), by setting the matrix q to be the same dimension as X.  However, at [Line 15](https://github.com/cvxr/TFOCS/blob/6c6e263123c80c7a6eb03f937e02ee6caf938352/prox_l1.m#L15) if q is a matrix,  ~isnumeric( q ) and ~isreal( q ) will return scalar values and any( q < 0 ) and all(q==0) will return vectors. This will lead to an error when doing the || operation.
The problem should easily be solved by using any( q < 0, 'all' ) and all( q==0, 'all' ), which will return a scalar regardless the dimension of q. I am wondering if we could make a PR to this so that prox_l1 could support vector and high-dimensional matrix as input. 
Thank you!

**Comment by stephenbeckr** [comment]
Good catch! Sounds like a simple fix. Yes, please make a PR and I'll incorporate it.

**Comment by Nick3151** [comment]
Thank you! I just made a PR with similar adaptations to some proximal functions that should accept matrix input. Let me know if there's any issue!

**Comment by stephenbeckr** [comment]
Thanks!  Though on second thought, maybe changing `any( lambda <= 0)` to `any( lambda(:))` instead of `any( lambda <= 0, 'all' )` is better, because the `any( ..., 'all')` syntax only works in R2018b and later [and since Matlab isn't free, a lot of people use old versions].  Could you revise (or just delete and make a new one) the PR to the `lambda(:)` syntax?  Thanks!

**Comment by Nick3151** [comment]
Good point! Just updated my PR with q(:) instead of 'any'
